import type { Metadata } from "next";
export const metadata: Metadata = { title: "Metodología" };

export default function MethodologyPage() {
  return (
    <main id="contenido" className="shell page-shell methodology">
      <header className="page-header"><p className="eyebrow">Método transparente y reproducible</p><h1>Metodología y limitaciones</h1><p>Las reglas son deterministas: los mismos resultados de entrada producen siempre la misma clasificación.</p></header>
      <aside className="limitation-notice"><strong>Aclaración obligatoria.</strong> Este análisis compara respuestas obtenidas desde la infraestructura del servidor de la aplicación. Una alerta representa una posible inconsistencia entre proveedores y no confirma por sí sola un ataque o la alteración del router del usuario.</aside>

      <section className="method-content">
        <nav className="method-index" aria-label="Contenido de metodología"><strong>Contenido</strong><a href="#protocolos">01 · Protocolos</a><a href="#consenso">02 · Consenso</a><a href="#clasificacion">03 · Clasificación</a><a href="#confianza">04 · Confianza</a><a href="#limitaciones">05 · Limitaciones</a><a href="#etica">06 · Ética</a></nav>
        <div className="method-articles">
          <article id="protocolos"><p className="eyebrow">01</p><h2>Tres transportes observados</h2><p><strong>DNS tradicional</strong> envía la pregunta directamente a los resolvedores públicos de Cloudflare y Google mediante el mecanismo DNS estándar. <strong>DoH</strong> encapsula la consulta en HTTPS y valida respuestas JSON de ambos proveedores. <strong>DoT</strong> envía un mensaje DNS binario dentro de una conexión TLS autenticada con el servicio de Quad9 sin bloqueo de amenazas por el puerto 853.</p><p>DoH y DoT protegen el transporte hasta el resolvedor, pero no convierten automáticamente su contenido en una verdad absoluta.</p></article>
          <article id="consenso"><p className="eyebrow">02</p><h2>Consenso seguro por ronda</h2><ol><li>Se comparan Cloudflare DoH, Google DoH y Quad9 DoT como organizaciones independientes.</li><li>El quórum siempre exige dos de las tres organizaciones; un fallo de transporte se abstiene.</li><li>Para respuestas positivas se comparan conjuntos de IP, sin depender del orden o del TTL.</li><li>NODATA y NXDOMAIN pueden formar consenso, pero se mantienen como resultados distintos.</li></ol><p>Timeout, error y transporte no disponible nunca se interpretan como respuestas DNS.</p></article>
          <article id="clasificacion"><p className="eyebrow">03</p><h2>Clasificación durante tres rondas</h2><div className="table-scroll"><table><thead><tr><th>Resultado</th><th>Regla principal</th></tr></thead><tbody><tr><td>Consistente</td><td>Consenso seguro y los dos DNS tradicionales coinciden durante tres rondas.</td></tr><tr><td>Advertencia</td><td>Existe evidencia útil, pero es parcial, dividida o cambia entre rondas.</td></tr><tr><td>Posible inconsistencia</td><td>El consenso seguro persiste y ambos DNS tradicionales quedan fuera durante tres rondas.</td></tr><tr><td>No concluyente</td><td>Faltan canales seguros, consenso o respuestas suficientes.</td></tr></tbody></table></div></article>
          <article id="confianza"><p className="eyebrow">04</p><h2>Confianza explicable</h2><p>La puntuación de 0 a 100 combina disponibilidad de consultas (30 %), protocolos representados (15 %), fuerza del consenso (25 %) y persistencia entre rondas (30 %). Una advertencia se limita a 79 y un resultado no concluyente a 49.</p><p><strong>No representa la probabilidad de que exista un ataque.</strong> Indica cuánta evidencia reunió el algoritmo para sostener su propia clasificación.</p></article>
          <article id="limitaciones"><p className="eyebrow">05</p><h2>Falsos positivos y límites</h2><ul><li>CDN, geolocalización, balanceo de carga y cambios de caché pueden entregar IP diferentes legítimas.</li><li>Las mediciones representan la región del servidor, no el router ni el DNS configurado por el visitante.</li><li>Las cinco rutas representan tres organizaciones: Cloudflare, Google y Quad9.</li><li>Un hosting puede bloquear UDP/TCP 53 o TCP 853. El sistema lo muestra como fallo, nunca como éxito simulado.</li><li>El sistema no valida por sí mismo cadenas DNSSEC ni inspecciona tráfico de red.</li></ul></article>
          <article id="etica"><p className="eyebrow">06</p><h2>Uso ético</h2><p>DNSSpoofDetector realiza consultas DNS normales a proveedores públicos. No modifica servidores, no altera el router, no captura paquetes, no ejecuta spoofing y no bloquea conexiones. Los escenarios de demostración utilizan exclusivamente redes reservadas para documentación.</p><p className="references">Referencias técnicas: <a href="https://www.rfc-editor.org/rfc/rfc1035" target="_blank" rel="noreferrer">RFC 1035</a>, <a href="https://www.rfc-editor.org/rfc/rfc7858" target="_blank" rel="noreferrer">RFC 7858</a> y <a href="https://www.rfc-editor.org/rfc/rfc8484" target="_blank" rel="noreferrer">RFC 8484</a>.</p></article>
        </div>
      </section>
    </main>
  );
}
